swagger: '2.0'
info:
  description: This is CREOL api specifications
  version: 0.1.0
  title: Creol
  termsOfService: 'http://creol.com/io/terms/'
  contact:
    email: apiteam@creol.fr
  license:
    name: ...
host: '###environment.apiUrl###'
basePath: /v2
schemes:
  - https
tags:
  - name: user-creds
    description: ''
  - name: gui-parameter-model
    description: ''
  - name: gui-parameter-value-model
    description: ''
  - name: gui-section-model
    description: ''
  - name: log-response
    description: ''  
  - name: admin-price
    description: ''
  - name: admin-zoning
    description: ''
  - name: admin-pop
    description: ''
  - name: study-export
    description: ''
  - name: oauth
    description: ''
  - name: fen-workspaceCQHD
    description: ''
  - name: fen-workspaceSingleCQHD
    description: ''
  - name: fen-cqhd-assign
    description: ''
  - name: fen-cqhd-unassign
    description: ''
  - name: fen-popWithDistance
    description: ''
  - name: fen-cqhd-validate
    description: ''
  - name: fen-cqhd-profiles
    description: ''
  - name: fen-cqhd-reject
    description: ''
  - name: fen-cqhd-search
    description: ''
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
securityDefinitions:
  admin_auth:
    type: oauth2
    authorizationUrl: 'http://studies.creol.com/oauth/login'
    flow: implicit
    scopes:
      admin: admin rights
  fen_auth:
    type: oauth2
    authorizationUrl: 'http://studies.creol.com/oauth/login'
    flow: implicit
    scopes:
      fen: fen rights
  api_key:
    type: apiKey
    name: Token
    in: header
externalDocs:
  description: Find out more about Creol
  url: 'http://creol.com'
